[package]
name = "untapped_scraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.21.2", features = ["full"] }
thirtyfour = "0.31.0"
color-eyre = "0.6.2"
rusqlite = "0.28.0"